# Generated by Django 6.0.4 on 2026-04-22 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROCESSINGRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SUM', 'Suma'), ('SUBTRACT', 'Resta'), ('MEAN', 'Media aritmética')], max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PROCESSING_rules', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'PROCESSING Rule',
                'verbose_name_plural': 'PROCESSING Rules',
                'ordering': ['-updated_at'],
            },
        ),
    ]
