# Generated by Django 6.0.4 on 2026-04-22 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='current_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PROCESSING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('FINISHED', 'FINISHED'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('FINISHED_at', models.DateTimeField(blank=True, null=True)),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='rules.PROCESSINGRule')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PROCESSING_executions', to=settings.AUTH_USER_MODEL)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='uploads.uploadedfile')),
            ],
            options={
                'verbose_name': 'PROCESSING Execution',
                'verbose_name_plural': 'PROCESSING Executions',
                'ordering': ['-version', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('uploaded_file', 'version'), name='unique_uploaded_file_version')],
            },
        ),
    ]
