# Generated by Django 6.0.4 on 2026-04-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN_ORG', 'Administrador de organización'), ('ANALYST', 'Analista')], default='ANALYST', max_length=20),
        ),
    ]
